//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvaHidrica.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class SPlcAddresses : global::System.Configuration.ApplicationSettingsBase {
        
        private static SPlcAddresses defaultInstance = ((SPlcAddresses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SPlcAddresses())));
        
        public static SPlcAddresses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX0.0")]
        public string ReadIsOpen1 {
            get {
                return ((string)(this["ReadIsOpen1"]));
            }
            set {
                this["ReadIsOpen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX0.1")]
        public string ReadIsOpen2 {
            get {
                return ((string)(this["ReadIsOpen2"]));
            }
            set {
                this["ReadIsOpen2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX0.3")]
        public string ReadPlcStatus {
            get {
                return ((string)(this["ReadPlcStatus"]));
            }
            set {
                this["ReadPlcStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.0")]
        public string WriteOpen1 {
            get {
                return ((string)(this["WriteOpen1"]));
            }
            set {
                this["WriteOpen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.1")]
        public string WriteOpen2 {
            get {
                return ((string)(this["WriteOpen2"]));
            }
            set {
                this["WriteOpen2"] = value;
            }
        }
    }
}
